[project]
name = "needmusicrobot"
version = "0.1.1"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.9.2",
    "deezer-python>=7.2.0",
    "pyrogram>=2.0.106",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "spotipy>=2.25.1",
    "tgcrypto>=1.2.5",
    "yt-dlp>=2025.9.26",
]
